[versions]
agp = "8.5.2"
kotlin = "2.2.20"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
recyclerview = "1.3.2"
viewpager2 = "1.1.0"
lifecycle = "2.9.4"

# Networking and Data Serialization
gson = "2.13.2"
retrofit = "3.0.0"
retrofit-converter = "2.11.0"
okhttp = "5.1.0"
moshi ="1.15.2"

# Hilt
hilt = "2.57.1"
ksp = "2.2.20-2.0.2"
nav-safe-args = "2.7.7"

#Firbase
firebaseCore = "21.1.1"
firebaseAnalytics = "22.1.2"
firebaseCrashlytics = "19.2.0"
firebaseCrashlyticsPlugin = "3.0.2"
firebaseBom = "33.3.0"

#Security
androidxSecurity = "1.1.0-alpha06"

#Google Play Services
playAppUpdate = "2.1.0"
playServicesBase = "18.5.0"
playServicesBasement = "18.4.0"
playServicesTasks = "18.2.0"
googleServicesPlugin = "4.4.3"

#Glide
glide ="4.16.0"

#Test
mockk = "1.14.6"
coroutine_test = "1.10.2"
hiltAndroidTesting = "2.57.2"
turbine = "1.2.1"
fragmentTesting = "1.8.9"
junit-jupiter = "5.12.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }

# Networking and Data Serialization
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit-converter" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

#Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

#Firebase Integration
firebase-core = {group = "com.google.firebase", name = "firebase-core", version.ref = "firebaseCore" }
firebase-analytics-ktx = {group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebaseAnalytics" }
firebase-crashlytics-ktx = {group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebaseCrashlytics" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx"}


#Security
androidx-security = {group = "androidx.security", name = "security-crypto", version.ref = "androidxSecurity" }

#Google Play Services
app-update = { module = "com.google.android.play:app-update", version.ref = "playAppUpdate" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "playAppUpdate" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
play-services-basement = { module = "com.google.android.gms:play-services-basement", version.ref = "playServicesBasement" }
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "playServicesTasks" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServicesPlugin" }

#Glide
glide = { module = "com.github.bumptech.glide:glide", version.ref ="glide"}


#Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
coroutine-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutine_test" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTesting" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragmentTesting" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "nav-safe-args" }

